# Generated by Django 2.0.5 on 2018-06-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temp', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=9, null=True)),
                ('yp_category', models.CharField(blank=True, max_length=100, null=True)),
                ('search_tree', models.TextField(blank=True, null=True)),
                ('email_data', models.TextField(blank=True, null=True)),
                ('yp_sub_category', models.CharField(blank=True, max_length=5000, null=True)),
                ('insurance', models.CharField(max_length=512, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('yp_street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('yp_city', models.CharField(blank=True, max_length=30, null=True)),
                ('yp_state', models.CharField(blank=True, max_length=3, null=True)),
                ('yp_zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('yp_image', models.CharField(blank=True, max_length=256, null=True)),
                ('yp_description', models.TextField(blank=True, null=True)),
                ('yp_email', models.TextField(blank=True, null=True)),
                ('yp_extra_info', models.TextField(blank=True, null=True)),
                ('yp_product_terms', models.TextField(blank=True, max_length=512, null=True)),
                ('yp_url', models.CharField(blank=True, max_length=512, null=True)),
                ('unionreporters_description', models.TextField(blank=True, null=True)),
                ('current_dentists', models.TextField(blank=True, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=256, null=True)),
                ('unionreporters_raw_address', models.CharField(blank=True, max_length=1024, null=True)),
                ('unionreporters_location', models.CharField(blank=True, max_length=512, null=True)),
                ('unionreporters_categories', models.TextField(blank=True, null=True)),
                ('unionreporters_url', models.CharField(blank=True, max_length=512, null=True)),
                ('unionreporters_phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
