# Generated by Django 2.0.5 on 2018-06-13 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=9, null=True)),
                ('yp_category', models.CharField(blank=True, max_length=100, null=True)),
                ('search_tree', models.TextField(blank=True, null=True)),
                ('email_data', models.TextField(blank=True, null=True)),
                ('yp_sub_category', models.CharField(blank=True, max_length=5000, null=True)),
                ('insurance', models.CharField(max_length=512, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('yp_street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('yp_city', models.CharField(blank=True, max_length=30, null=True)),
                ('yp_state', models.CharField(blank=True, max_length=3, null=True)),
                ('yp_zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('yp_image', models.CharField(blank=True, max_length=256, null=True)),
                ('yp_description', models.TextField(blank=True, null=True)),
                ('yp_email', models.TextField(blank=True, null=True)),
                ('yp_extra_info', models.TextField(blank=True, null=True)),
                ('yp_product_terms', models.TextField(blank=True, max_length=512, null=True)),
                ('yp_url', models.CharField(blank=True, max_length=512, null=True)),
                ('unionreporters_description', models.TextField(blank=True, null=True)),
                ('current_dentists', models.TextField(blank=True, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=256, null=True)),
                ('unionreporters_raw_address', models.CharField(blank=True, max_length=1024, null=True)),
                ('unionreporters_location', models.CharField(blank=True, max_length=512, null=True)),
                ('unionreporters_categories', models.TextField(blank=True, null=True)),
                ('unionreporters_url', models.CharField(blank=True, max_length=512, null=True)),
                ('unionreporters_phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('company', 'Company'), ('person', 'Person')], max_length=50)),
                ('data_type', models.CharField(choices=[('source', 'Source'), ('behavior', 'Behavior'), ('meta', 'Meta')], max_length=50)),
                ('data_table', models.CharField(max_length=100)),
                ('data_table_fk', models.BigIntegerField()),
                ('lead_name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': '_leads',
            },
        ),
        migrations.CreateModel(
            name='ScrapeYellowpagesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('universal_citystate', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('search_terms', models.CharField(max_length=200)),
                ('extra_info', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(max_length=200)),
                ('product_terms', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': '_source_scrape_yellowpages',
            },
        ),
    ]
