# Generated by Django 2.0.5 on 2018-06-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('company', 'Company'), ('person', 'Person')], max_length=50)),
                ('lead_name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': '_leads',
            },
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='temp',
        ),
        migrations.CreateModel(
            name='SourceScrapeYellowpages',
            fields=[
                ('lead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='directories.Lead')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1054)),
                ('email', models.CharField(max_length=100)),
                ('search_terms', models.CharField(max_length=200)),
                ('extra_info', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(max_length=200)),
                ('product_terms', models.CharField(max_length=1024)),
            ],
            bases=('directories.lead',),
        ),
    ]
