# Generated by Django 2.0.5 on 2018-06-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeyellowpagesrecord',
            name='name',
            field=models.CharField(default='none', max_length=256),
            preserve_default=False,
        ),
    ]
