# Generated by Django 2.0.5 on 2018-06-07 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_auto_20180606_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescrapeyellowpages',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2018, 6, 7, 2, 50, 51, 698099, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
