# Generated by Django 2.0.5 on 2018-06-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_sourcescrapeyellowpages_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SourceScrapeYellowpages',
            new_name='ScrapeYellowpages',
        ),
    ]
