# Generated by Django 2.0.5 on 2018-06-08 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_auto_20180607_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeYellowpagesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('universal_citystate', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('search_terms', models.CharField(max_length=200)),
                ('extra_info', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(max_length=200)),
                ('product_terms', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': '_source_scrape_yellowpages',
            },
        ),
        migrations.RemoveField(
            model_name='scrapeyellowpages',
            name='lead_ptr',
        ),
        migrations.AddField(
            model_name='lead',
            name='data_table',
            field=models.CharField(default='hello world', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='data_table_fk',
            field=models.BigIntegerField(default='recorded before column creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='data_type',
            field=models.CharField(choices=[('source', 'Source'), ('behavior', 'Behavior'), ('meta', 'Meta')], default='recorded before column creation', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScrapeYellowpages',
        ),
    ]
